# Generated by Django 2.1.2 on 2018-11-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0002_auto_20180920_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='description',
            field=models.TextField(blank=True, help_text='Markdown is partially supported.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Only you can see this trail.', verbose_name='Private'),
        ),
    ]
